# Config explanation - https://github.com/Prunt/RestrictedCreative/wiki/Config-explanation
database:
  type: sqlite
  username: root
  password: ''
  host: localhost
  port: 3306
  database: rc_database
  table:
    blocks: rc_blocks
    inventories: rc_invs

commands:
  rc:
    description: 'RestrictedCreative main command used for reloading, statistics and other.'
    usage: '&cCorrect usage: /<command> <reload|block|i-am-sure-i-want-to-delete-all-plugin-data-from-database>'
    aliases:
    - 'restrictedcreative'
  survival:
    description: 'Enter survival mode.'
    usage: '&cCorrect usage: /<command> [player]'
    aliases:
    - 'gm0'
    - 'gms'
  creative:
    description: 'Enter creative mode.'
    usage: '&cCorrect usage: /<command> [player]'
    aliases:
    - 'gm1'
    - 'gmc'
  adventure:
    description: 'Enter adventure mode.'
    usage: '&cCorrect usage: /<command> [player]'
    aliases:
    - 'gm2'
    - 'gma'
  spectator:
    description: 'Enter spectator mode.'
    usage: '&cCorrect usage: /<command> [player]'
    aliases:
    - 'gm3'
    - 'gmsp'
    

general:
  converter:
    creative-control: cc_
    share-control: blocks
  disabled-worlds:
   - 'pure-survival-world'
   - 'pure-creative-world'
  saving:
    interval: 6000
    inventories:
      enabled: true
      purge:
        survival: 90
        creative: 30
  
creative:
  armor:
    enabled: true
    color: 16711680
  permissions:
    enabled: false
    list:
    - 'prefix.creative'
    - '-prefix.survival'

tracking:
  blocks:
    enabled: true
    exclude:
    - 'AIR'
  worldedit:
    enabled: false
    extended: false
  inventory:
    enabled: true

limit:
  regions: # requires WorldGuard or GriefPrevention
    owner-based:
      enabled: false
      allow-members: false # requires WorldGuard
    whitelist:
      enabled: false
      list:
      - 'building_competition'
  moving:
    enabled: false
    below-y: -1
    above-y: -1
  interact:
    inventories: true
    entities: true
    breeding: true
  item:
    drop: true
    pickup: true
    throw: true
  commands:
  - '(.*)(buy|sell)(.*)'
  - '(.*)(chest)(.*)'
  combat:
    pvp: true
    pve: true
  creation:
    wither: true
    snow-golem: true
    iron-golem: true
  
confiscate:
  invalid-items: true # NBT check requires ProtocolLib
  middle-click: true
  items:
    enabled: true
    material:
    - 'BARRIER'
    - 'CHAIN_COMMAND_BLOCK'
    - 'COMMAND_BLOCK'
    - 'COMMAND_BLOCK_MINECART'
    - 'REPEATING_COMMAND_BLOCK'
    - 'SPAWNER'
    - 'DRAGON_EGG'
    - 'RED_MUSHROOM_BLOCK'
    - 'BROWN_MUSHROOM_BLOCK'
    - 'GRASS_PATH'
    - 'STRUCTURE_BLOCK'
    - 'STRUCTURE_VOID'
    - 'VOID_AIR'
    name:
    - 'Cash'
    - 'Spawn Egg'
    - 'Sapling'
    lore:
    - '$'

disable:
  placing:
  - 'BEDROCK'
  - 'END_PORTAL_FRAME'
  - 'TNT'
  breaking:
  - 'BEDROCK'
  - 'END_PORTAL_FRAME'
  interacting:
    in-hand:
    - 'SPLASH_POTION'
    - 'LINGERING_POTION'
    - 'FLINT_AND_STEEL'
    - 'FIRE_CHARGE'
    - 'EXPERIENCE_BOTTLE'
    - 'INK_SAC'
    - 'ENDER_EYE'
    - 'EGG'
    - 'LAVA_BUCKET'
    on-ground:
    - 'JUKEBOX'
    - 'FLOWER_POT'
    - 'SIGN'
    - 'WALL_SIGN'
    