name: RestrictedCreative
version: 2.0
description: Extremely lightweight, but fully-featured and customizable Creative mode limiter.
author: Prunt
main: me.prunt.restrictedcreative.Main
website: 'https://www.spigotmc.org/resources/restrictedcreative.42790/'
softdepend: [ProtocolLib, WorldEdit, WorldGuard, GriefPrevention, Vault]
api-version: 1.13

commands:
  rc:
    permission: rc.commands.rc
  creative:
    permission: rc.commands.creative
  survival:
    permission: rc.commands.survival
  adventure:
    permission: rc.commands.adventure
  spectator:
    permission: rc.commands.spectator

permissions:
  rc.*:
    description: Allows everything.
    default: false
    children:
      rc.commands.*: true
      rc.bypass.*: true

  rc.commands.*:
    description: Allows every command.
    default: OP
    children:
      rc.commands.rc: true
      rc.commands.creative: true
      rc.commands.survival: true
      rc.commands.adventure: true
      rc.commands.spectator: true
      rc.commands.reload: true
      rc.commands.delete: true
      rc.commands.block: true
  rc.bypass.*:
    description: Allows to bypass everything.
    default: false
    children:
      rc.bypass.general.worlds.disable-plugin: true
      rc.bypass.creative.armor: true
      rc.bypass.creative.permissions: true
      rc.bypass.tracking.blocks: true # per Material enum
      rc.bypass.tracking.entities: true # per EntityType enum
      rc.bypass.tracking.worldedit: true
      rc.bypass.tracking.inventory.*: true
      rc.bypass.limit.regions.owner-based: true
      rc.bypass.limit.regions.whitelist: true
      rc.bypass.limit.moving: true
      rc.bypass.limit.interact.inventories: true # per InventoryType enum
      rc.bypass.limit.interact.entities: true # per EntityType enum
      rc.bypass.limit.interact.breeding: true # per EntityType enum
      rc.bypass.limit.item.drop: true # per Material enum
      rc.bypass.limit.item.pickup: true # per Material enum
      rc.bypass.limit.item.throw: true # per Material enum
      rc.bypass.limit.commands: true
      rc.bypass.limit.combat.pvp: true
      rc.bypass.limit.combat.pve: true # per EntityType enum
      rc.bypass.limit.creation.wither: true
      rc.bypass.limit.creation.snow-golem: true
      rc.bypass.limit.creation.iron-golem: true
      rc.bypass.confiscate.invalid-items: true
      rc.bypass.confiscate.middle-click: true
      rc.bypass.confiscate.items.material: true # per Material enum
      rc.bypass.confiscate.items.name: true
      rc.bypass.confiscate.items.lore: true
      rc.bypass.disable.placing: true # per Material enum
      rc.bypass.disable.interacting.in-hand: true # per Material enum
      rc.bypass.disable.interacting.on-ground: true # per Material enum
      rc.bypass.disable.breaking: true # per Material enum

  rc.bypass.tracking.inventory.*:
    description: Allows to bypass inventory separation.
    default: false
    children:
      rc.bypass.tracking.inventory.contents: true
      rc.bypass.tracking.inventory.xp: true
      rc.bypass.tracking.inventory.effects: true
    
    
  rc.commands.rc:
    description: Allows to use the main command.
    default: OP
  rc.commands.creative:
    description: Allows to enter the creative mode.
    default: OP
  rc.commands.survival:
    description: Allows to enter the survival mode.
    default: OP
  rc.commands.adventure:
    description: Allows to enter the adventure mode.
    default: OP
  rc.commands.spectator:
    description: Allows to enter the spectator mode.
    default: OP
  rc.commands.reload:
    description: Allows to use the reload command.
    default: OP
  rc.commands.delete:
    description: Allows to use the delete command.
    default: OP
  rc.commands.convert:
    description: Allows to use the conversion command.
    default: OP
  rc.commands.block:
    description: Allows to use the block info command.
    default: OP
    
  rc.bypass.general.worlds.disable-plugin:
    description: Allows to go into disabled worlds in creative mode.
    default: false
  rc.bypass.limit.regions.whitelist:
    description: Allows to enter creative mode and place blocks/items outside whitelisted regions in creative mode.
    default: false
    
  rc.bypass.separate-invs:
    description: Allows to have same inventory for both creative and survival/adventure.
    default: false
  rc.bypass.separate-effects:
    description: Allows to have same potion effects for both creative and survival/adventure.
    default: false
  rc.bypass.remove-invalid-items:
    description: Allows to use invalid items (also items with custom NBT).
    default: false
  rc.bypass.armor:
    description: Allows to bypass armor forcing in creative mode.
    default: false
  rc.bypass.track.save-blocks:
    description: Allows to place blocks in creative mode (and/or using WorldEdit) that will not be saved.
    default: false
  rc.bypass.track.remove-drops:
    description: Allows to get drops from blocks placed in creative mode.
    default: false
  rc.bypass.disable.interact.inventories:
    description: Allows to interact with inventories in creative mode.
    default: false
  rc.bypass.disable.interact.signs:
    description: Allows to interact with signs in creative mode.
    default: false
  rc.bypass.disable.interact.entities:
    description: Allows to interact with entities in creative mode.
    default: false
  rc.bypass.disable.interact.breeding:
    description: Allows to breed animals in creative mode.
    default: false
  rc.bypass.disable.item.drop:
    description: Allows to drop items in creative mode.
    default: false
  rc.bypass.disable.item.pickup:
    description: Allows to pick items up in creative mode.
    default: false
  rc.bypass.disable.item.throw:
    description: Allows to throw and shoot items in creative mode.
    default: false
  rc.bypass.disable.commands:
    description: Allows to use disabled commands in creative mode.
    default: false
  rc.bypass.disable.move:
    description: Allows to move below and above disabled Y levels in creative mode.
    default: false
  rc.bypass.disable.middle-click:
    description: Allows to copy inventory contents with middle-click in creative mode.
    default: false
  rc.bypass.combat.pvp:
    description: Allows to hit other players while in creative mode.
    default: false
  rc.bypass.combat.pve:
    description: Allows to hit other entities while in creative mode.
    default: false
  rc.bypass.blacklist.items.name:
    description: Allows to have items with blacklisted names in their inventory while in creative mode.
    default: false
  rc.bypass.blacklist.items.lore:
    description: Allows to have items with blacklisted lores in their inventory while in creative mode.
    default: false
  rc.bypass.blacklist.place:
    description: Allows to place items/blocks listed in blacklist while in creative mode.
    default: false
  rc.bypass.blacklist.interact:
    description: Allows to use/interact with items/blocks listed in blacklist while in creative mode.
    default: false
  rc.bypass.blacklist.break:
    description: Allows to break items/blocks listed in blacklist while in creative mode.
    default: false